#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]
use tauri::{Manager,State};
use rusqlite::{Connection,params};
use serde_json::{Value,json};
use std::{sync::Mutex,path::{Path,PathBuf},fs,io::{Read,Write}};
use sha2::{Sha256,Digest};
use base64::Engine;
struct Store{root:PathBuf,guard:Mutex<()>}
type Result<T>=std::result::Result<T,String>;
fn err(e:impl std::fmt::Display)->String{e.to_string()}
fn connect(root:&Path)->Result<Connection>{let c=Connection::open(root.join("treasurer.sqlite")).map_err(err)?;c.execute_batch("PRAGMA foreign_keys=ON; CREATE TABLE IF NOT EXISTS state(id INTEGER PRIMARY KEY CHECK(id=1),data TEXT NOT NULL); CREATE TABLE IF NOT EXISTS evidence(id TEXT PRIMARY KEY,name TEXT NOT NULL,mime TEXT NOT NULL); ").map_err(err)?;Ok(c)}
fn initial()->Value{json!({"revision":0,"categories":[],"years":[],"entries":[],"receipts":[],"audit":[],"incoming":""})}
fn get(c:&Connection)->Result<Value>{let s:Option<String>=c.query_row("SELECT data FROM state WHERE id=1",[],|r|r.get(0)).optional().map_err(err)?;s.map(|v|serde_json::from_str(&v).map_err(err)).unwrap_or(Ok(initial()))}
use rusqlite::OptionalExtension;
fn put(c:&Connection,d:&Value)->Result<()>{c.execute("INSERT INTO state VALUES(1,?1) ON CONFLICT(id) DO UPDATE SET data=excluded.data",[d.to_string()]).map_err(err)?;Ok(())}
fn locked(d:&Value,e:&Value)->bool{d["years"].as_array().unwrap().iter().any(|y|y["periods"].as_array().unwrap().iter().any(|p|p["locked"]==true&&p["start"].as_str()<=e["date"].as_str()&&e["date"].as_str()<=p["end"].as_str()))}
fn audit(d:&mut Value,action:String){let now=std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap().as_millis().to_string();d["audit"].as_array_mut().unwrap().push(json!({"at":now,"action":action}));d["revision"]=json!(d["revision"].as_u64().unwrap_or(0)+1);}
#[tauri::command] fn load_data(s:State<Store>)->Result<Value>{let _g=s.guard.lock().map_err(err)?;get(&connect(&s.root)?)}
#[tauri::command] fn save_data(s:State<Store>,mut data:Value,action:String)->Result<Value>{let _g=s.guard.lock().map_err(err)?;let mut c=connect(&s.root)?;let tx=c.transaction().map_err(err)?;let old=get(&tx)?;if old["revision"]!=data["revision"]{return Err("Records changed. Reload before saving.".into());}
for key in ["years","entries","receipts","categories","audit"]{if !data[key].is_array(){return Err("Invalid records".into());}}
for e in old["entries"].as_array().unwrap(){let next=data["entries"].as_array().unwrap().iter().find(|n|n["id"]==e["id"]);if locked(&old,e)&&next!=Some(e){return Err("Cannot change a transaction in a locked period".into());}}
for e in data["entries"].as_array().unwrap(){let prev=old["entries"].as_array().unwrap().iter().find(|n|n["id"]==e["id"]);if prev!=Some(e)&&locked(&old,e){return Err("Cannot write into a locked period".into());}}
for y in old["years"].as_array().unwrap(){for (i,p) in y["periods"].as_array().unwrap().iter().enumerate(){if p["locked"]==true{let next=data["years"].as_array().unwrap().iter().find(|n|n["id"]==y["id"]);if next.is_none()||next.unwrap()["periods"][i]["start"]!=p["start"]||next.unwrap()["periods"][i]["end"]!=p["end"]{return Err("Unlock the period before changing its dates".into());}}}}
data["audit"]=old["audit"].clone();audit(&mut data,action);put(&tx,&data)?;tx.commit().map_err(err)?;Ok(data)}
fn ingest(root:&Path,c:&Connection,name:String,bytes:Vec<u8>)->Result<Value>{let ext=Path::new(&name).extension().and_then(|s|s.to_str()).unwrap_or("").to_lowercase();let mime=match ext.as_str(){"pdf" if bytes.starts_with(b"%PDF")=>"application/pdf","png" if bytes.starts_with(b"\x89PNG\r\n\x1a\n")=>"image/png","jpg"|"jpeg" if bytes.starts_with(&[255,216,255])=>"image/jpeg",_=>return Err("Only valid PDF, PNG and JPEG files are supported".into())};let id=format!("{:x}",Sha256::digest(&bytes));fs::create_dir_all(root.join("evidence")).map_err(err)?;let path=root.join("evidence").join(&id);if !path.exists(){fs::write(&path,bytes).map_err(err)?;}c.execute("INSERT OR IGNORE INTO evidence VALUES(?1,?2,?3)",params![id,name,mime]).map_err(err)?;let mut d=get(c)?;if let Some(r)=d["receipts"].as_array().unwrap().iter().find(|r|r["id"]==id){return Ok(r.clone());}let r=json!({"id":id,"name":name,"mime":mime,"categoryId":"","status":"unlinked"});d["receipts"].as_array_mut().unwrap().push(r.clone());audit(&mut d,"Imported evidence".into());put(c,&d)?;Ok(r)}
#[tauri::command] fn import_bytes(s:State<Store>,name:String,bytes:Vec<u8>)->Result<Value>{let _g=s.guard.lock().map_err(err)?;ingest(&s.root,&connect(&s.root)?,name,bytes)}
#[tauri::command] fn import_paths(s:State<Store>,paths:Vec<String>)->Result<Vec<Value>>{let _g=s.guard.lock().map_err(err)?;let c=connect(&s.root)?;paths.iter().map(|p|{let path=Path::new(p);ingest(&s.root,&c,path.file_name().unwrap_or_default().to_string_lossy().into(),fs::read(path).map_err(err)?)}).collect()}
#[tauri::command] fn scan_folder(s:State<Store>)->Result<Vec<String>>{let _g=s.guard.lock().map_err(err)?;let c=connect(&s.root)?;let d=get(&c)?;let dir=d["incoming"].as_str().unwrap_or("");if dir.is_empty(){return Ok(vec![]);}let mut errors=vec![];for entry in fs::read_dir(dir).map_err(err)?{let p=entry.map_err(err)?.path();if p.is_file()&&matches!(p.extension().and_then(|s|s.to_str()).unwrap_or("").to_lowercase().as_str(),"pdf"|"png"|"jpg"|"jpeg"){let r=fs::read(&p).map_err(err).and_then(|b|ingest(&s.root,&c,p.file_name().unwrap().to_string_lossy().into(),b));if let Err(e)=r{errors.push(format!("{}: {}",p.display(),e));}}}Ok(errors)}
#[tauri::command] fn read_evidence(s:State<Store>,id:String)->Result<String>{if id.len()!=64||!id.bytes().all(|b|b.is_ascii_hexdigit()){return Err("Invalid evidence identifier".into());}let b=fs::read(s.root.join("evidence").join(id)).map_err(err)?;Ok(base64::engine::general_purpose::STANDARD.encode(b))}
#[tauri::command] fn write_export(path:String,bytes:Vec<u8>)->Result<()>{fs::write(path,bytes).map_err(err)}
fn backup(root:&Path,path:&Path)->Result<()>{let c=connect(root)?;let snap=root.join("snapshot.sqlite");if snap.exists(){fs::remove_file(&snap).map_err(err)?;}let mut dest=Connection::open(&snap).map_err(err)?;rusqlite::backup::Backup::new(&c,&mut dest).map_err(err)?.run_to_completion(100,std::time::Duration::from_millis(5),None).map_err(err)?;drop(dest);let mut files=vec![("treasurer.sqlite".to_string(),fs::read(&snap).map_err(err)?)];let mut stmt=c.prepare("SELECT id FROM evidence").map_err(err)?;let ids=stmt.query_map([],|r|r.get::<_,String>(0)).map_err(err)?;for id in ids{let id=id.map_err(err)?;files.push((format!("evidence/{id}"),fs::read(root.join("evidence").join(&id)).map_err(err)?));}let checks:serde_json::Map<String,Value>=files.iter().map(|(n,b)|(n.clone(),json!(format!("{:x}",Sha256::digest(b))))).collect();let manifest=json!({"version":1,"checksums":checks});let mut zip=zip::ZipWriter::new(fs::File::create(path).map_err(err)?);let opts=zip::write::SimpleFileOptions::default().compression_method(zip::CompressionMethod::Deflated);for (name,b) in files{zip.start_file(name,opts).map_err(err)?;zip.write_all(&b).map_err(err)?;}zip.start_file("manifest.json",opts).map_err(err)?;zip.write_all(manifest.to_string().as_bytes()).map_err(err)?;zip.finish().map_err(err)?;fs::remove_file(snap).map_err(err)?;Ok(())}
#[tauri::command] fn create_backup(s:State<Store>,path:String)->Result<()>{let _g=s.guard.lock().map_err(err)?;backup(&s.root,Path::new(&path))}
#[tauri::command] fn restore_backup(s:State<Store>,path:String)->Result<Value>{let _g=s.guard.lock().map_err(err)?;restore(&s,path)}
fn restore(s:&Store,path:String)->Result<Value>{let mut z=zip::ZipArchive::new(fs::File::open(path).map_err(err)?).map_err(err)?;let manifest:Value={let mut f=z.by_name("manifest.json").map_err(err)?;let mut t=String::new();f.read_to_string(&mut t).map_err(err)?;serde_json::from_str(&t).map_err(err)?};if manifest["version"]!=1{return Err("Unsupported backup version".into());}let checks=manifest["checksums"].as_object().ok_or("Invalid manifest")?;let staging=s.root.join("restore-staging");if staging.exists(){fs::remove_dir_all(&staging).map_err(err)?;}fs::create_dir_all(staging.join("evidence")).map_err(err)?;
for (n,hash) in checks{if n!="treasurer.sqlite"&&!(n.starts_with("evidence/")&&n.len()==73&&n[9..].bytes().all(|b|b.is_ascii_hexdigit())){return Err("Unsafe backup path".into());}let mut f=z.by_name(n).map_err(err)?;if f.size()>512*1024*1024{return Err("Backup file too large".into());}let mut b=vec![];f.read_to_end(&mut b).map_err(err)?;if json!(format!("{:x}",Sha256::digest(&b)))!=*hash{return Err("Backup checksum mismatch".into());}fs::write(staging.join(n),b).map_err(err)?;}
if !checks.contains_key("treasurer.sqlite"){return Err("Missing backup database".into());}let restored=connect(&staging)?;let check:String=restored.query_row("PRAGMA integrity_check",[],|r|r.get(0)).map_err(err)?;if check!="ok"{return Err("Damaged database".into());}let mut d=get(&restored)?;for r in d["receipts"].as_array().ok_or("Invalid receipts")?{let id=r["id"].as_str().ok_or("Invalid receipt")?;if !checks.contains_key(&format!("evidence/{id}")){return Err("Missing evidence in backup".into());}}drop(restored);let stamp=std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap().as_secs();backup(&s.root,&s.root.join(format!("safety-{stamp}.zip")))?;
// Stage is fully validated before replacing data. Copy evidence first, commit state last.
for f in fs::read_dir(staging.join("evidence")).map_err(err)?{let f=f.map_err(err)?;fs::create_dir_all(s.root.join("evidence")).map_err(err)?;fs::copy(f.path(),s.root.join("evidence").join(f.file_name())).map_err(err)?;}
let mut current=connect(&s.root)?;let tx=current.transaction().map_err(err)?;tx.execute("DELETE FROM evidence",[]).map_err(err)?;for r in d["receipts"].as_array().unwrap(){tx.execute("INSERT INTO evidence VALUES(?1,?2,?3)",params![r["id"].as_str(),r["name"].as_str(),r["mime"].as_str()]).map_err(err)?;}d["incoming"]=json!("");audit(&mut d,"Restored backup; incoming folder disconnected".into());put(&tx,&d)?;tx.commit().map_err(err)?;fs::remove_dir_all(staging).map_err(err)?;Ok(d)}
fn main(){tauri::Builder::default().plugin(tauri_plugin_dialog::init()).setup(|app|{let root=app.path().app_data_dir()?;fs::create_dir_all(root.join("evidence"))?;app.manage(Store{root,guard:Mutex::new(())});Ok(())}).invoke_handler(tauri::generate_handler![load_data,save_data,import_bytes,import_paths,scan_folder,read_evidence,write_export,create_backup,restore_backup]).run(tauri::generate_context!()).expect("Unable to start Treasurer");}

#[cfg(test)]
mod tests {
use super::*;
static NEXT:std::sync::atomic::AtomicUsize=std::sync::atomic::AtomicUsize::new(0);
fn store()->Store {let root=std::env::temp_dir().join(format!("treasurer-test-{}-{}-{}",std::process::id(),NEXT.fetch_add(1,std::sync::atomic::Ordering::SeqCst),std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap().as_nanos()));fs::create_dir_all(root.join("evidence")).unwrap();Store{root,guard:Mutex::new(())}}
#[test] fn evidence_deduplicates_and_persists(){let s=store();let c=connect(&s.root).unwrap();let a=ingest(&s.root,&c,"one.pdf".into(),b"%PDF-1.4 fixture".to_vec()).unwrap();let b=ingest(&s.root,&c,"two.pdf".into(),b"%PDF-1.4 fixture".to_vec()).unwrap();assert_eq!(a["id"],b["id"]);assert_eq!(get(&c).unwrap()["receipts"].as_array().unwrap().len(),1);drop(c);assert_eq!(get(&connect(&s.root).unwrap()).unwrap()["receipts"][0]["id"],a["id"]);fs::remove_dir_all(s.root).unwrap();}
#[test] fn rejects_wrong_file_signature(){let s=store();assert!(ingest(&s.root,&connect(&s.root).unwrap(),"fake.pdf".into(),b"not pdf".to_vec()).is_err());fs::remove_dir_all(s.root).unwrap();}
#[test] fn backup_roundtrip_preserves_original_and_clears_folder(){let a=store();let c=connect(&a.root).unwrap();let r=ingest(&a.root,&c,"invoice.pdf".into(),b"%PDF-1.4 fixture".to_vec()).unwrap();let mut d=get(&c).unwrap();d["incoming"]=json!("/old/mac/path");put(&c,&d).unwrap();drop(c);let archive=a.root.join("copy.zip");backup(&a.root,&archive).unwrap();let b=store();let restored=restore(&b,archive.to_string_lossy().into()).unwrap();assert_eq!(restored["receipts"][0]["id"],r["id"]);assert_eq!(restored["incoming"],"");assert_eq!(fs::read(b.root.join("evidence").join(r["id"].as_str().unwrap())).unwrap(),b"%PDF-1.4 fixture");assert!(fs::read_dir(&b.root).unwrap().any(|f|f.unwrap().file_name().to_string_lossy().starts_with("safety-")));fs::remove_dir_all(a.root).unwrap();fs::remove_dir_all(b.root).unwrap();}
#[test] fn corrupt_archive_does_not_replace_records(){let s=store();let c=connect(&s.root).unwrap();ingest(&s.root,&c,"invoice.pdf".into(),b"%PDF-1.4 fixture".to_vec()).unwrap();let before=get(&c).unwrap();drop(c);let bad=s.root.join("bad.zip");fs::write(&bad,b"corrupted").unwrap();assert!(restore(&s,bad.to_string_lossy().into()).is_err());assert_eq!(get(&connect(&s.root).unwrap()).unwrap(),before);fs::remove_dir_all(s.root).unwrap();}
#[test] fn checksum_mismatch_is_rejected(){let s=store();let bad=s.root.join("bad.zip");let mut z=zip::ZipWriter::new(fs::File::create(&bad).unwrap());let opts=zip::write::SimpleFileOptions::default();z.start_file("manifest.json",opts).unwrap();z.write_all(br#"{"version":1,"checksums":{"treasurer.sqlite":"bad"}}"#).unwrap();z.start_file("treasurer.sqlite",opts).unwrap();z.write_all(b"bad database").unwrap();z.finish().unwrap();assert!(restore(&s,bad.to_string_lossy().into()).unwrap_err().contains("checksum"));fs::remove_dir_all(s.root).unwrap();}
}
